# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MaskCreator
                                 A QGIS plugin
 Creates a mask that surrounds all features within a map.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-04-16
        copyright            : (C) 2022 by Angus Hunt
        email                : angusfhunt@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MaskCreator class from file MaskCreator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mask_creator import MaskCreator
    return MaskCreator(iface)
